<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpotifyFavoritesTool.Karaoke\SpotifyFavoritesTool.Karaoke.csproj" />
    <ProjectReference Include="..\SpotifyFavoritesTool.Models\SpotifyFavoritesTool.Models.csproj" />
    <ProjectReference Include="..\SpotifyFavoritesTool.UI\SpotifyFavoritesTool.UI.csproj" />
    <ProjectReference Include="..\SpotifyFavoritesTool.Windows\SpotifyFavoritesTool.Windows.csproj" />
    <ProjectReference Include="..\SpotifyFavoritesTool.Translation\SpotifyFavoritesTool.Translation.csproj" />
    <ProjectReference Include="..\SpotifyFavoritesTool.Translation.DeepL\SpotifyFavoritesTool.Translation.DeepL.csproj" />
    <ProjectReference Include="..\SpotifyFavoritesTool.Translation.Libre\SpotifyFavoritesTool.Translation.Libre.csproj" />
    <ProjectReference Include="..\SpotifyFavoritesTool.Translation.Google\SpotifyFavoritesTool.Translation.Google.csproj" />
  </ItemGroup>

</Project>
